name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://cldr-steven-matison.github.io/feed.xml"
          # This template forces the image to show and makes the title a link
          template: |
            <a href="$url">
              <img src="$postImage" width="400px" alt="$title" />
            </a>
            <br/>
            <a href="$url"><b>$title</b></a>
            <br/><br/>
          # Ensures each post starts on a new line
          tag_post_pre_newline: true